name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every day at 3:00pm UTC
  schedule:
    - cron: '0 15 * * *'

jobs:
  ci:
    name: CI
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      composer_install: true
      # installer contains a sample behat.yml file, though there are no behat tests to run
      endtoend: false
      # require the following in ci.yml rather than composer.json require-dev specifically for installer because unlike
      # regular modules, require-dev will get installed to projects during `composer create-project silverstripe/installer`
      composer_require_extra: silverstripe/recipe-testing:^3 silverstripe/frameworktest:^1 mikey179/vfsstream:^1.6.10
      extra_jobs: |
        - php: 8.1
          phpunit: true
          phpunit_suite: recipe-cms
        ## Added behat tests:
        - php: 8.1
          endtoend: true
          endtoend_suite: cms
          endtoend_config: vendor/silverstripe/cms/behat.yml
        - php: 8.1
          endtoend: true
          endtoend_suite: versioned-admin
          endtoend_config: vendor/silverstripe/versioned-admin/behat.yml
 